### ISSUE TITLE
Visual Editor does not work

### ISSUE THREAD

**Issue by muddro1** [mattieha/slider-button-card#23]
**Checklist:**

- [X ] I updated to the latest version available
- [ X] I cleared the cache of my browser

**Release with the issue:1.10

**Last working release (if known):**

**Browser and Operating System:** Mobile app, windows 10, chrome, firefox

**Description of problem:**

The visual editor does not save any of the changed values in the card. Has to be done through the YAML/Code editor.

**Comment by mattieha** [comment]
Thanks for your feedback, I've added to the roadmap.
I'll make this highest priority now!

**Comment by mattieha** [comment]
@muddro1  This should be fixed in v.1.5.1, can you please test this?

**Comment by muddro1** [comment]
Just tried it out, still doesn't record changes made in visual editor.

**Comment by mattieha** [comment]
@muddro1 Thanks for testing, did you clear your browser cache?
Does the error occur when your adding new cards or modifying already added cards?

**Comment by nepozs** [comment]
For me it also does not work. Visual Editor just shows everything wchich is configured in yaml, but you can't change anything - "save" button isn't activated after any changes, it is still only "close".

**Comment by mattieha** [comment]
Damn I hoped the new release would fix the issues you are reporting.
The problem is I can't reproduce them, so it's trial and error.
I'll give it another try on Sunday....

**Comment by muddro1** [comment]
Works same as @nepozs stated. Tried on new card after clearing cache. Trying through the HA android all

**Comment by alanpi** [comment]
cant use the visual editor too getting erros in console 
Uncaught TypeError: Cannot assign to read only property 'direction' of object '#<Object>'
    at Me (slider-button-card.js:200)
    at Me (slider-button-card.js:200)
    at HTMLElement._changeValue (slider-button-card.js:417)
    at HTMLElement._valueChangedSelect (slider-button-card.js:417)
    at dt.handleEvent (slider-button-card.js:82)
    at HTMLElement.__boundHandleEvent (slider-button-card.js:82)
    at k (app.bcb38ac1.js:13497)
    at Object.x [as fn] (app.bcb38ac1.js:13497)
    at w (app.bcb38ac1.js:13497)
    at app.bcb38ac1.js:13497

**Comment by FrankJaco** [comment]
Sorry to say that I also have the issue. Nothing in the visual editor sticks. I have applied todays update, I have cleared the cashe, and restarted HA completely. Issue occurs on Chrome, Firefox and Edge.
But keep up the good work though...  I REALLY like the look and feel of your button sliders. I look forward to when you find the cause of this bug.  Thanks for your efforts!
FJ

**Comment by jeffphilly** [comment]
Same issue here. I'm sure someone smarter then me will figure it out!! This card seems like it will inevitably be part of the core and become the norm for HA!!

**Comment by mattieha** [comment]
I've made a new release: v1.5.3 could u guys please test if this version fixes the problems?

**Comment by alanpi** [comment]
Fixed for me

**Comment by mattieha** [comment]
@muddro1 @jeffphilly @FrankJaco @nepozs 
Can you please confirm it's now working for you too?

**Comment by nepozs** [comment]
Yes, it works (tested both browsers: Firefox and Chrome).
