### ISSUE TITLE
Assign to readonly property

### ISSUE THREAD

**Issue by felix63** [mattieha/slider-button-card#25]
**Release with the issue:** 1.1.0

**Browser and Operating System:**

Chromium on Raspberry

Error in log: slider-button-card/slider-button-card.js:200:19530 TypeError: Attempted to assign to readonly property.
`
type: horizontal-stack
cards:
  - type: custom:slider-button-card
    entity: light.wc_kamer
    slider:
      percentage: true
      direction: left-right
      background: solid
      use_state_color: true
      use_percentage_bg_opacity: false
      show_track: false
      force_square: false
    show_name: false
    show_state: true
    icon:
      show: true
      use_state_color: true
      rotate: false
      tap_action:
        action: more-info
    action_button:
      mode: toggle
      icon: mdi:power
      show: true
      show_spinner: true
      tap_action:
        action: toggle
  - type: custom:slider-button-card
    entity: light.hanging_lamp
    slider:
      percentage: true
      direction: left-right
      background: solid
      use_state_color: true
      use_percentage_bg_opacity: false
      show_track: false
      force_square: false
    show_name: false
    show_state: true
    icon:
      show: true
      use_state_color: true
      rotate: false
      tap_action:
        action: more-info
    action_button:
      mode: toggle
      icon: mdi:power
      show: true
      show_spinner: true
      tap_action:
        action: toggle
`

**Comment by mattieha** [comment]
@felix63 This should be fixed in v.1.5.1, can you please test this?

**Comment by felix63** [comment]
Yes. It's fixed, the error is gone. I still can't edited the card in the visual editor tough. Changes are not recognized and are not saved.
